### ISSUE TITLE
响应拦截器返回类型不灵活

### ISSUE THREAD

**Issue by CS-liujf** [notbucai/taro-request#12]
在如下的例子中
```ts
import taroRequest from '@bucai/taro-request';
const request = taroRequest.create({
    baseURL: 'https://www.baidu.com',
    timeout: 6 * 1000
})

request.interceptors.response.use(
    response => {
        const res = response.data
        if(res.code===1)
            return res //ts 报错，类型不匹配
    }
)
```
响应拦截器不能返回`res`，而必须是`res.data`，这导致拦截器使用起来不灵活

**Comment by notbucai** [comment]
> 在如下的例子中
> 
> ```ts
> import taroRequest from '@bucai/taro-request';
> const request = taroRequest.create({
>     baseURL: 'https://www.baidu.com',
>     timeout: 6 * 1000
> })
> 
> request.interceptors.response.use(
>     response => {
>         const res = response.data
>         if(res.code===1)
>             return res //ts 报错，类型不匹配
>     }
> )
> ```
> 
> 响应拦截器不能返回`res`，而必须是`res.data`，这导致拦截器使用起来不灵活

这里解决也只能临时解决，在使用（post、get）还是没办法读取拦截器类型。
所以看看还是直接any？

**Comment by notbucai** [comment]
fix: https://github.com/notbucai/taro-request/commit/a5583577ced282991c8c086399ecc9b229aac948
