### ISSUE TITLE
麻烦把console.log去掉一下

### ISSUE THREAD

**Issue by mingtianyihou33** [notbucai/taro-request#2]
![image](https://user-images.githubusercontent.com/22953606/102954829-623e2d00-450f-11eb-9630-0a1c17e9e7ae.png)

**Comment by mingtianyihou33** [comment]
taro-request/src/core/dispatchRequest.js
第32行

**Comment by notbucai** [comment]
[https://github.com/notbucai/taro-request/commit/d59bc6a2ab232e9249f9d7829d4336bd4f4dd5a4](https://github.com/notbucai/taro-request/commit/d59bc6a2ab232e9249f9d7829d4336bd4f4dd5a4)
